export const services = [
  {
    id: 1,
    title: "Software Development",
    description: "Building tailored software solutions for your unique business needs — from web apps to enterprise ERP, SaaS platforms, and robust APIs.",
    icon: "Globe",
    color: "from-blue-500/20 to-indigo-500/20",
    border: "hover:border-blue-500/40",
    glow: "rgba(99,102,241,0.3)",
    tags: ["ERP / ERPNext", "WebApp", "APIs", "SaaS", "PaaS"],
  },
  {
    id: 2,
    title: "AI Solutions",
    description: "Designing and deploying bespoke AI models to solve your most complex challenges and unlock powerful data-driven insights.",
    icon: "Cpu",
    color: "from-emerald-500/20 to-green-500/20",
    border: "hover:border-emerald-500/40",
    glow: "rgba(16,185,129,0.3)",
    tags: ["Custom Models", "AI Consulting", "Integration", "LLM"],
  },
  {
    id: 3,
    title: "Cloud & DevOps",
    description: "Designing and managing robust cloud environments to ensure seamless operations, full automation, and secure digital growth at scale.",
    icon: "Cloud",
    color: "from-cyan-500/20 to-teal-500/20",
    border: "hover:border-cyan-500/40",
    glow: "rgba(6,182,212,0.3)",
    tags: ["Infrastructure", "Automation", "Scalability", "CI/CD"],
  },
  {
    id: 4,
    title: "Martech & CRM",
    description: "Optimizing your MarTech stack spanning CRM, analytics, marketing automation, and customer data platforms for measurable ROI.",
    icon: "Layers",
    color: "from-violet-500/20 to-purple-500/20",
    border: "hover:border-violet-500/40",
    glow: "rgba(139,92,246,0.3)",
    tags: ["CRM", "ADTech", "Dashboards", "Analytics"],
  },
  {
    id: 5,
    title: "Marketing Strategy",
    description: "Crafting data-driven marketing strategies — GTM plans, SEO, SEM, and social media — that align with your goals and drive sustainable growth.",
    icon: "Palette",
    color: "from-rose-500/20 to-pink-500/20",
    border: "hover:border-rose-500/40",
    glow: "rgba(236,72,153,0.3)",
    tags: ["GTM", "SEO / SEM", "Social Media", "DMM"],
  },
  {
    id: 6,
    title: "2D & 3D Animation",
    description: "Immersive visual storytelling through 2D/3D animation, CGI, VFX, SFX, and AR/VR experiences crafted for global brands.",
    icon: "Sparkles",
    color: "from-orange-500/20 to-amber-500/20",
    border: "hover:border-orange-500/40",
    glow: "rgba(249,115,22,0.3)",
    tags: ["CGI / VFX", "AR / VR", "3D Modelling", "SFX"],
  },
];

export const stats = [
  { value: "150+", label: "Projects Delivered" },
  { value: "50+", label: "Countries Served" },
  { value: "10+", label: "Years Experience" },
  { value: "100+", label: "Happy Clients" },
];

export const portfolio = [
  {
    id: 1,
    title: "HRMS Platform",
    category: "Enterprise SaaS",
    description: "End-to-end human resources management platform with payroll, performance tracking, and compliance automation for mid-to-large enterprises.",
    image: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&q=80",
    tags: ["ERPNext", "Frappe", "Python", "React"],
    color: "from-indigo-500 to-violet-600",
  },
  {
    id: 2,
    title: "Lead & Sales Automation",
    category: "Martech",
    description: "Intelligent pipeline management with lead scoring, automated follow-ups, and conversion optimization — driving 40% faster deal closures.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
    tags: ["CRM", "AI", "Node.js", "Automation"],
    color: "from-cyan-500 to-blue-600",
  },
  {
    id: 3,
    title: "E-commerce Platform",
    category: "Retail Tech",
    description: "Scalable omnichannel storefront with integrated payments, real-time inventory, logistics management, and customer analytics.",
    image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80",
    tags: ["Next.js", "Stripe", "ERPNext", "AWS"],
    color: "from-emerald-500 to-teal-600",
  },
  {
    id: 4,
    title: "Custom ERP Solution",
    category: "Enterprise",
    description: "Modular enterprise resource planning tailored to complex workflows — from procurement and finance to production and supply chain.",
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80",
    tags: ["Frappe", "ERPNext", "Python", "REST API"],
    color: "from-rose-500 to-pink-600",
  },
  {
    id: 5,
    title: "Financial Market Platform",
    category: "Fintech",
    description: "Trading platform and portfolio dashboard with real-time market data, compliance reporting, and risk analytics for financial institutions.",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80",
    tags: ["React", "WebSocket", "Python", "PostgreSQL"],
    color: "from-amber-500 to-orange-600",
  },
  {
    id: 6,
    title: "Document Management (DMS)",
    category: "Enterprise SaaS",
    description: "Centralized document storage with versioning, role-based access control, full-text search, and audit trails for regulated industries.",
    image: "https://images.unsplash.com/photo-1568992687947-868a62a9f521?w=800&q=80",
    tags: ["Next.js", "S3", "Elasticsearch", "Node.js"],
    color: "from-purple-500 to-indigo-600",
  },
];

export const process = [
  {
    step: "01",
    title: "Discover",
    description: "Deep-dive into your business goals, operational challenges, and technical constraints through structured workshops and research.",
    icon: "Search",
    color: "text-indigo-400",
    bg: "from-indigo-500/10 to-indigo-500/5",
  },
  {
    step: "02",
    title: "Design",
    description: "Craft pixel-perfect wireframes, system architecture, and design systems that align with your brand and scale with your business.",
    icon: "Pen",
    color: "text-violet-400",
    bg: "from-violet-500/10 to-violet-500/5",
  },
  {
    step: "03",
    title: "Develop",
    description: "Build with clean, tested, production-ready code using agile sprints, continuous integration, and transparent progress tracking.",
    icon: "Code2",
    color: "text-cyan-400",
    bg: "from-cyan-500/10 to-cyan-500/5",
  },
  {
    step: "04",
    title: "Deploy",
    description: "Launch with zero-downtime deployments, performance monitoring, proactive support, and ongoing optimization to keep you ahead.",
    icon: "Rocket",
    color: "text-emerald-400",
    bg: "from-emerald-500/10 to-emerald-500/5",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Rajesh Mehta",
    role: "CTO, FinCore Technologies",
    avatar: "RM",
    color: "from-indigo-500 to-violet-500",
    rating: 5,
    text: "TechBird transformed our legacy ERP into a modern, cloud-native platform in record time. Their deep expertise in ERPNext and AI integration made a huge impact on our operations.",
  },
  {
    id: 2,
    name: "Priya Nair",
    role: "Head of Digital, RetailPlus",
    avatar: "PN",
    color: "from-cyan-500 to-blue-500",
    rating: 5,
    text: "The e-commerce platform TechBird built for us scaled from 0 to 10k orders per day without a hiccup. Their cloud & DevOps expertise is genuinely world-class.",
  },
  {
    id: 3,
    name: "Arjun Sharma",
    role: "Founder, LegalEdge",
    avatar: "AS",
    color: "from-emerald-500 to-teal-500",
    rating: 5,
    text: "Our litigation management system went live ahead of schedule. TechBird understood the nuances of legal workflows and delivered a product our team actually loves using.",
  },
  {
    id: 4,
    name: "Sunita Patel",
    role: "VP Operations, MedServe",
    avatar: "SP",
    color: "from-rose-500 to-pink-500",
    rating: 5,
    text: "From AI-powered patient analytics to HRMS integration, TechBird delivered end-to-end. Their team is responsive, technically sharp, and genuinely invested in your success.",
  },
];

export const pricing = [
  {
    name: "Starter",
    price: "₹49,999",
    period: "project",
    description: "Perfect for startups and small businesses looking to digitize fast.",
    features: [
      "Up to 5 pages / modules",
      "Responsive web design",
      "Basic SEO optimization",
      "2 revision rounds",
      "30-day post-launch support",
      "Source code handover",
    ],
    cta: "Get Started",
    highlight: false,
    color: "from-slate-500/10 to-slate-600/5",
    border: "border-white/8",
  },
  {
    name: "Growth",
    price: "₹1,49,999",
    period: "project",
    description: "For scaling companies building serious digital products.",
    features: [
      "Full web / ERP application",
      "Custom design system",
      "API integrations",
      "Auth & payments",
      "AI feature integration",
      "3-month support",
      "Analytics dashboard",
    ],
    cta: "Most Popular",
    highlight: true,
    color: "from-indigo-500/15 to-violet-500/10",
    border: "border-indigo-500/40",
  },
  {
    name: "Enterprise",
    price: "Custom",
    period: "tailored",
    description: "End-to-end solutions for complex enterprise digital transformation.",
    features: [
      "Unlimited scope",
      "Dedicated team",
      "ERPNext / Frappe expertise",
      "AI & ML integration",
      "24/7 support SLA",
      "On-premise or cloud",
      "Custom contracts",
    ],
    cta: "Contact Us",
    highlight: false,
    color: "from-slate-500/10 to-slate-600/5",
    border: "border-white/8",
  },
];

export const blogPosts = [
  {
    id: 1,
    title: "Why ERPNext is the Future of Open-Source Enterprise Management",
    excerpt: "Discover how ERPNext and the Frappe framework are empowering businesses to replace expensive legacy ERP systems with flexible, scalable alternatives.",
    category: "ERP / ERPNext",
    date: "Apr 28, 2025",
    readTime: "7 min read",
    color: "from-indigo-500/20 to-violet-500/10",
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&q=80",
  },
  {
    id: 2,
    title: "AI Integration in Business: From Hype to Real-World ROI",
    excerpt: "How TechBird's clients are using custom AI models and LLM pipelines to automate operations, reduce costs, and unlock insights at scale.",
    category: "AI Solutions",
    date: "Apr 14, 2025",
    readTime: "8 min read",
    color: "from-emerald-500/20 to-cyan-500/10",
    image: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&q=80",
  },
  {
    id: 3,
    title: "Digital Transformation Roadmap: A Practical Guide for Enterprises",
    excerpt: "A step-by-step framework for enterprise leaders planning their digital transformation journey — from assessment to full-scale deployment.",
    category: "Strategy",
    date: "Mar 31, 2025",
    readTime: "10 min read",
    color: "from-violet-500/20 to-pink-500/10",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=600&q=80",
  },
];

export const clients = [
  "Education", "Healthcare", "Legal & Finance", "Retail", "Manufacturing",
  "BPO & Call Centers", "Hospitality", "Fintech", "E-commerce", "IT & SaaS",
  "Logistics", "Real Estate", "Media & Entertainment", "NGO & Govt", "Pharma",
];
